import LogicFormalization.Chapter1.Section2

import LogicFormalization.Chapter2.Section1.Admissibility
import LogicFormalization.Chapter2.Section1.Arity
import LogicFormalization.Chapter2.Section1.DecidableReading
import LogicFormalization.Chapter2.Section1.Homework
import LogicFormalization.Chapter2.Section1.NormalForms
import LogicFormalization.Chapter2.Section1.Notation
import LogicFormalization.Chapter2.Section1.Prop'
import LogicFormalization.Chapter2.Section1.Prop'Lemmas
import LogicFormalization.Chapter2.Section1.Tautologies

import LogicFormalization.Chapter2.Section2.Basic
import LogicFormalization.Chapter2.Section2.Coloring
import LogicFormalization.Chapter2.Section2.Completeness
import LogicFormalization.Chapter2.Section2.Homework
import LogicFormalization.Chapter2.Section2.Notation

import LogicFormalization.Chapter2.Section3.Basic
import LogicFormalization.Chapter2.Section3.Defs
import LogicFormalization.Chapter2.Section3.Homework
import LogicFormalization.Chapter2.Section3.Meta

import LogicFormalization.Chapter2.Section4.Homework
import LogicFormalization.Chapter2.Section4.Term
import LogicFormalization.Chapter2.Section4.Var
